---

version: "3.6"
services:
  bosmapper_server:
    <<: &bosmapper_server
      build:
        context: .
        target: production
      environment:
        - MASTER_TOKEN=${MASTER_TOKEN}
      expose:
        - 80

  caddy:
    image: caddy:latest
    volumes:
      - caddydata:/data
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bosmapper_server
    networks:
      - proxynet

volumes:
  caddydata:
