---

version: "3.6"
services:

  bosmapper_server:
    <<: &bosmapper_server
      build:
        context: .
        target: development
      command: ["/start-reload.sh"]
      environment:
        - MASTER_TOKEN=dev_token
      ports:
        - "8080:80"
      volumes:
        - ./app:/app
